workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
  - deploy

deploy_app:
  tags:
    - shell
    - oracle
  stage: deploy
  script:
    - echo "Running unit tests...."
